### ISSUE TITLE
Code Re-organization

### ISSUE THREAD

**Issue by yde773786** [CSC207-UofT/course-project-java-sapiens#31]
- Use Cases have been incorrectly identified as Controllers. Make required refactors as well as creation of controllers.
- The View is interacting with entities (Eg: UserActivity with User). Prevent this.

**Comment by kevicai** [comment]
@TynerG @yde773786  Please make the current User, Customer, and Deliveryman Manager classes store an instance attribute of their respective Entity, and implement all the setter and getter methods that Commodity has. So whenever we want to get info about a User, for example, their name, we don't use the User Entity's methods directly, we put the User into a Manager and use the Manager's getter methods. OrderManager and ShoppingListManager have already been implemented in this way, you guys can just refer to them when implementing.

**Comment by kevicai** [comment]
@yde773786 Please make a Gateway for each of our Use Cases that needs something to be saved.

**Comment by kevicai** [comment]
@TynerG @sidsachdev12   Please make the current User, Customer (maybe Tyner can do this), and Deliveryman (maybe Sid can do this) Manager classes store an instance attribute of their respective Entity, and implement all the setter and getter methods that Commodity has. So whenever we want to get info about a User, for example, their name, we don't use the User Entity's methods directly, we put the User into a Manager and use the Manager's getter methods. Also, the Use Cases don't need their save get methods. OrderManager and ShoppingListManager have already been implemented in this way, you guys can just refer to them when implementing.

**Comment by TynerG** [comment]
CustomerManager completed.

**Comment by sidsachdev12** [comment]
DeliverymanManager completed.
